# Generated by Django 2.0.4 on 2018-04-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20180429_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseimage',
            options={'ordering': ['search_text'], 'verbose_name': 'SearchImagem', 'verbose_name_plural': 'BaseImage'},
        ),
        migrations.AlterField(
            model_name='baseimage',
            name='search_text',
            field=models.TextField(max_length=150, verbose_name='search_text'),
        ),
    ]
