# Generated by Django 2.0.4 on 2018-04-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20180429_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseimage',
            name='search_text',
            field=models.TextField(blank=True, null=True, verbose_name='search_text'),
        ),
    ]
