# Generated by Django 2.0.4 on 2018-05-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20180519_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseimage',
            name='descriptorORB',
            field=models.TextField(blank=True, null=True, verbose_name='descriptorORB'),
        ),
    ]
