# Generated by Django 2.0.4 on 2018-05-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_baseimage_descriptororb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseimage',
            name='descriptorORB',
        ),
    ]
