# Generated by Django 2.0.4 on 2018-05-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_baseimage_descriptorcedd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseimage',
            name='search_image',
            field=models.ImageField(blank=True, null=True, upload_to='tmp', verbose_name='path_imagem'),
        ),
    ]
